version: "3"
services:
  jenkins:
    build: ./jenkins/
    command: sudo /etc/init.d/jenkins start
    links:
      - sonar
    ports:
      - "8080:8080"  
    networks:
      - backend
  sonar:
    build: ./sonar/
    command: /home/sonaradmin/sonarqube-7.5/bin/linux-x86-64/sonar.sh
    networks:
      - backend
    ports:
      - "9000:9000" 
networks:
 backend:
    driver: "bridge"
